replicaCount: 2

image:
  repository: ghcr.io/fanninggh/flask-devops
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 5000

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

config:
  flaskEnv: production
  logLevel: INFO

probes:
  liveness:
    path: /health
    initialDelaySeconds: 15
    periodSeconds: 10
  readiness:
    path: /ready
    initialDelaySeconds: 5
    periodSeconds: 5
